app:
  build: .
  volumes:
      - .:/code
  working_dir: /code
  entrypoint: "./phpunit.sh"
  tty: true
  stdin_open: true
  environment:
    - IMPALA_DB_HOST=impala
    - IMPALA_DB_PORT=21050
    - IMPALA_DB_DATABASE=default
    - IMPALA_DB_USER=root
    - IMPALA_DB_PASSWORD=
  links:
    - impala

impala:
  image: quay.io/keboola/impala-docker
  ports:
    - "21050:21050"
