version: '2'

services:
  app: &main
    image: keboola/db-writer-impala
    build: .
    working_dir: /code
    tty: true
    stdin_open: true
    environment:
      - DB_HOST=impala
      - DB_PORT=21050
      - DB_DATABASE=default
      - DB_USER=root
      - DB_PASSWORD=
    links:
      - impala
  dev:
    <<: *main
    image: keboola/db-writer-impala-dev
    volumes:
      - .:/code

  impala:
    image: quay.io/keboola/impala-docker
    ports:
      - "21050:21050"
